---
title: "Compute flow based domains"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


antaresFlowbased package allows generation of flow based domains.

## 1 - Generation of domains

The funciton *computeFB()* generate flow based domains from PTDF. Param **PTDF** must be the path of PTDF file, by default it's the PTDF file of 2017 FB. 
The PTDF file must be a csv file wich **;** for sep, **,** for dec and the following columns :

* **Id_day** : Id of typical day
* **Period** : Hour
* **BE** : Face for be
* **DE** : Face for de
* **FR** : Face for fr
* **NL** : Face for nl
* **RAM_0** : B

In output of this function, a directory is create. The name of directory is informed by the param **outputName**. In this direcrory you have the following files :

* **coefficients_Antares.csv** : Coefficient of face for antares
* **fichier_b_final.csv** : Faces for eatch typical day and hour
* **domainesFB.RDS** : table which importants elements of optimisation, (points, errors ,...)
* **reports** : a directory, created only if **reports** param is true. Contians a html report for eatch typical day.

## 2 - Visualisation and diffusion

You can visualised domains with function **runAppError**. 