---
title: "Utilisation du package AntaresFlowbased "
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Francais}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

Le package antaresFlowbased permet de lancer des études **flowbased** à partir du logiciel antares.

## 1 - Initialisation de l'étude :

L'initialisation de l'étude se fait via la fonction *initFlowBased()*. Cela se traduit par l'écriture des 4 fichiers suivant dans le répertoire */user/flowbased*, ainsi que la modification temporaire de la configuration du projet : 

* second_member.txt
* weight.txt
* scenario.txt
* ts.txt

Cette fonction utilise par défaut des fichiers présents dans le packages.

Avant toute chose, il est nécéssaire d'indiquer l'étude antares sur laquelle nous souhaitons travailler via la fonction *setSimulationPath()* du package **antaresRead** :

```{r, eval=FALSE}
antaresRead::setSimulationPath("D:/exemple_test", 0)

# initialisation de l'étude flowbased
initFlowBased()
```


## 2 - Lancement des simulations

Vous devez lancer les simulations directement depuis antares.
